branch-defaults:
  master:
    environment: main
global:
  application_name: node-eb
  branch: master
  default_ec2_keyname: null
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  repository: null
  # your aws profile with access and secret keys set
  # comment this setting when using CI/CD (e.g. Codebuild)
  # profile: default
  sc: git
  workspace_type: Application
